apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argsynctest
  name: argsynctest
  namespace: kubeflow
spec:
  containers:
  - image: nginx
    name: argsynctest
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
