apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argsynctest2
  name: argsynctest2
  namespace: kubeflow
spec:
  containers:
  - image: nginx
    name: argsynctest2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
